/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_PUBLIC_AUTH_ISSUER: string;
  readonly VITE_PUBLIC_ZERO_URL: string;
  readonly VITE_PUBLIC_DEV: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
